### ISSUE TITLE
Initialization fails if pnpm is not installed

### ISSUE THREAD

**Issue by klaascuvelier** [nrwl/ts-aoc-starter#2]
If `pnpm` is not installed, the starter fails

```
npx create-ts-aoc-starter@latest
Need to install the following packages:
  create-ts-aoc-starter@1.0.2
Ok to proceed? (y) y
🎄🎄🎄 Creating your Typescript Advent of Code Starter Repo... 🎄🎄🎄
⠋ Installing dependencies with pnpm/bin/sh: pnpm: command not found
node:internal/errors:867
  const err = new Error(message);
              ^

Error: Command failed: pnpm --version
/bin/sh: pnpm: command not found
```

Looking at the stacktrace, this might be something that should be fixed in the `create-nx-workspace` package?

```  
at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at getPackageManagerVersion (/Users/klaas/.npm/_npx/5caca1ad1c6c1e6f/node_modules/create-nx-workspace/src/utils/package-manager.js:82:50)
    at getPackageManagerCommand (/Users/klaas/.npm/_npx/5caca1ad1c6c1e6f/node_modules/create-nx-workspace/src/utils/package-manager.js:33:23)
```

---

Thanks for the package, the video and the AOC promo too :D

**Comment by ZackDeRose** [comment]
just dropped 1.0.3 - updated to use just npm for now. Thanks for submitting the issue!
