### ISSUE TITLE
Run example fails to load undefined file 

### ISSUE THREAD

**Issue by drdreo** [nrwl/ts-aoc-starter#3]
In the docs it refers to run `nx day-1-a --data=sample` . This command fails on Windows with
```sh
 nx run aoc:day-1-a --data=sample

> tsx day-1/a --data=sample

node:internal/fs/promises:638
  return new FileHandle(await PromisePrototypeThen(
                        ^

Error: ENOENT: no such file or directory, open 'D:\DEV\Projects\aoc-24\day-NaN\undefined.data.--data=sample.txt'
    at async open (node:internal/fs/promises:638:25)
    at async readFile (node:internal/fs/promises:1245:14)
    at readData (D:\DEV\Projects\aoc-24\utils.ts:20:17)
    at runSolution (D:\DEV\Projects\aoc-24\utils.ts:6:16)
    at <anonymous> (D:\DEV\Projects\aoc-24\day-1\a.ts:9:1) {
  errno: -4058,

```

**Comment by scarletczen** [comment]
Yeah getting the same error on Windows.

**Comment by HDv2b** [comment]
I know it's not a cross-OS solution, but local fix would be:

```
import chalk from 'chalk';
import { readFile } from 'fs/promises';
import { join } from 'path';

export async function runSolution(solution: (data: string[]) => any) {
  const data = await readData();
  const answer = await solution(data);
  console.log(chalk.bgGreen('Your Answer:'), chalk.green(answer));
}

export async function readData() {
  const [_, fullPath, dataSet] = process.argv as
    | [string, string, string]
    | [string, string];
  console.log(fullPath);
  const puzzle = fullPath.split('\\').slice(-2).join('\\');
  console.log(puzzle);
  const [day, part] = puzzle
    .split('\\')
    .map((x, i) => (i === 0 ? +x.split('-')[1] : x)) as [number, 'a' | 'b'];
  const fileName = createFileName(day, part, dataSet);
  console.log('filename', fileName);
  const data = (await readFile(fileName)).toString().replaceAll('\r', '').split('\n');
  return data;
}

function createFileName(day: number, part: 'a' | 'b', dataSet?: string) {
  return join(`day-${day}`, `${part}.data${dataSet ? `.${dataSet}` : ''}.txt`);
}
```

**Comment by erikwski** [comment]
Same error here, @HDv2b your solution is working. Thx

**Comment by kongnayeon** [comment]
It seems the same issue exists on macOS. On macOS, updating the code as shown below works well:

```
export async function readData() {
  const [_, fullPath, ...args] = process.argv;

  const dataSetArg = args.find((arg) => arg.startsWith('--data='));
  const dataSet = dataSetArg ? dataSetArg.split('=')[1] : undefined;

  const puzzle = fullPath.split('/').slice(-2).join('/');
  const [day, part] = puzzle
    .split('/')
    .map((x, i) => (i === 0 ? +x.split('-')[1] : x)) as [number, 'a' | 'b'];
  const fileName = createFileName(day, part, dataSet);
  const data = (await readFile(fileName)).toString().split('\n');
  return data;
}
```

**Comment by ghost** [comment]
Thanks @kongnayeon your solution is working 👍
